version: '3'
services:
    docker_radius:
        image: "hatobus/docker_raduis"
        ports:
            - "10000:10000"
    redis:
        image: "redis:latest"
        ports:
            - "6379:6379"
        volumes:
            - "./data/redis:/data"
