version: '3'
services:
    redis:
        image: "redis:latest"
        ports:
            - "6379:6379"

    router:
        image: "vyos-builder"
        ports:
            - "10000:10000"
        privileged: true
        volumes:
            - "$PWD:/vyos"
        command: /sbin/init
